"""Add gender default. 

Revision ID: 24d87566757b
Revises: 18a13d4d91bc
Create Date: 2022-08-22 18:52:59.750596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24d87566757b'
down_revision = '18a13d4d91bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
