"""Change role column from char to string. 

Revision ID: d84864bb47bb
Revises: 24d87566757b
Create Date: 2022-08-22 18:56:31.398133

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd84864bb47bb'
down_revision = '24d87566757b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'gender', default='non binary'),
    op.alter_column('users', 'role', type_=sa.String(), default='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
